### ISSUE TITLE
Remove Anthony Romaine's Profile

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#103]
This employee needs to be Removed from the UNLV-FIA Team Page. 

Employee Name: Anthony Romaine.

### Employee Information to Remove:
- Name
- Job Description
- Room Number
- Phone Number
- Email
- Biography
- Proficient Skills List
- Improvement Goals List
- Profile Image

### Important Notes:
- Ensure your newly removed employee hasn't disrupted the functionality/information of any existing employee
- Make sure the employee's profile picture & modal-launch button is removed
- Make sure the employee's Bootstrap modal is removed

**Comment by Kelvyn-Meyers** [comment]
Confirming @aromaine-unlv has removed his own profile alongside his PR to fix issue #56:
![image](https://user-images.githubusercontent.com/72825162/175091433-92436440-c0ee-4675-8194-77c509b6e696.png)

**QA-CERTIFIED**
