### ISSUE TITLE
Add Joe Tschida's profile to UNLV-FIA webpage

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#106]
This employee needs to be added to the UNLV-FIA Team Page. You can base your changes on existing employee profiles.

### Employee Information:
- Name: Joe Tschida
- Job Description: Data Modeler
- Room Number: [insert room number or skip if not applicable]
- Phone Number: [insert phone number or skip if not applicable]
- Email: joseph.tschida@unlv.edu
- Biography: Please use the attached resume in the comment below to draft a bio for Joe.
- Proficient Skills List: 
•	Data Modeling (ERwin / Conceptual via MS Visual Studio)
•	Data Integration (Informatica)
•	Reporting & Analysis (Business Objects / Microsoft Power BI / SQL)
•	SQL Database (Oracle / Microsoft SQL Server / Salesforce)
•	Problem Solving
•	Analytics / Data Profiling
•	Business / Technical Liaison
•	Data Governance

- Improvement Goals List: see resume or email joe if needed
- Image: Email sent 10/27/22.

### Important Notes:
- Ensure the new employee is added alphabetically to the list (leave Brenda & Gretchen as the first two no matter what)
- Ensure newly added images are similar in size (200x200) or that they are cropped/expanded evenly to fit size requirements
- Ensure newly added divs, buttons, dialogs, etc. are given unique IDs (if an ID was necessary for that element)
- Ensure your newly added employee hasn't disrupted the functionality/information of any existing employee

**Comment by renkesn** [comment]
[DM Resume - Tschida, J.docx](https://github.com/UNLV-FIA/UNLV-FIA-Group/files/9883022/DM.Resume.-.Tschida.J.docx)

**Comment by renkesn** [comment]
![Image](https://user-images.githubusercontent.com/65931068/200424580-0a502aa1-e531-4633-9fef-f25fc0feeeba.jpg)

**Comment by renkesn** [comment]
Hi @SudiptiSharma can you please update Joe's bio to say the following? Thanks for your hard work on this!

Joe Tschida began working with UNLV-FIA as a Data Modeler in October of 2022. Having been in the industry since 1990, Joe has 23 years of experience as a Data Warehouse Architect where he built data platforms, gained experience in data integration techniques, and tooled with dozens of data projects. With the UNLV-FIA team, his aim is to leverage his skills as a data architect, modeler, developer, and analyst in ways that will promote enterprise efficiency and lean capabilities. He also wants to assist in efforts that will result in strategic and operational improvements via better insights and enhanced abilities to make decisions.

**Comment by Kelvyn-Meyers** [comment]
@renkesn 
The second round of changes are now available for QA testing. You may need to clear your cache to see the current profiles!
