### ISSUE TITLE
Add Sunil Manzoor profile to the UNLV-FIA webpage

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#107]
This employee needs to be added to the UNLV-FIA Team Page. You can base your changes on existing employee profiles.

### Employee Information:
- Name: Sunil Manzoor
- Job Description: Software Engineer
- Room Number: [insert room number or skip if not applicable]
- Phone Number: [insert phone number or skip if not applicable]
- Email: sunil.manzoor@unlv.edu
- Biography: Please use the attached resume in the comment below to draft a bio for Sunil.
- Proficient Skills List:  Eclipse, Netbeans, PhpStorm, VN, Git, Trello, JIRA, Filezilla, AWS,
Codecommit, PDF-Lib, Javascript, NodeJS, ReactJS, AngularJS, Vue.js, jQuery, HTML5, CSS3, Ajax, Bootstrap, Material-UI,
Tailwind, JQuery Plugin Development, C/C++, Java, JavaScript, Asterisk, PHP, MySQL, NoSQL (MongoDB)
- Improvement Goals List: see resume or email Sunil if needed
- Image: Email sent 10/27/22.

### Important Notes:
- Ensure the new employee is added alphabetically to the list (leave Brenda & Gretchen as the first two no matter what)
- Ensure newly added images are similar in size (200x200) or that they are cropped/expanded evenly to fit size requirements
- Ensure newly added divs, buttons, dialogs, etc. are given unique IDs (if an ID was necessary for that element)
- Ensure your newly added employee hasn't disrupted the functionality/information of any existing employee

### Attachments: 
[Manzoor_CV_R0131351.pdf](https://github.com/UNLV-FIA/UNLV-FIA-Group/files/9883047/Manzoor_CV_R0131351.pdf)

**Comment by renkesn** [comment]
![Sunil Photo](https://user-images.githubusercontent.com/65931068/198403763-02c5bfec-49a6-4cbd-836f-439e5a9adc77.jpg)

**Comment by renkesn** [comment]
Hi @SudiptiSharma, can you please update Sunil's bio and his proficient skills section to the below information. 

Thanks!

Sunil's Bio: 

Sunil completed his Masters in Computer Science from Quaid I Azam University, Pakistan in 2016. He is an experienced full stack Software Engineer with expertise in all aspects of the software development life cycle, including requirements analysis, design, development, and production support. He is proficient at designing and formulating test automation frameworks and writing code in various languages. Sunil believes in thinking outside the box to find unique solutions to difficult engineering problems. In his free time, Sunil enjoys hiking, playing cricket, and spending time with his family. 

Proficient skills:

Eclipse, AWS, NodeJS, ReactJS, AngularJS, Vue.js, jQuery, HTML5, CSS3, Ajax, Bootstrap, Material-UI, Tailwind, jQuery Plugin Development, C/C++, Java, JavaScript, Asterisk, PHP, MySQL, NoSQL (MongoDB)

**Comment by Kelvyn-Meyers** [comment]
@renkesn 
The second round of changes are now available for QA testing. You may need to clear your cache to see the current profiles!
