### ISSUE TITLE
Remove Patricia Payton from UNLV-FIA Website

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#110]
This employee needs to be Removed from the UNLV-FIA Team Page. 

Employee Name: Patricia Payton.

### Employee Information to Remove:
- Name
- Job Description
- Room Number
- Phone Number
- Email
- Biography
- Proficient Skills List
- Improvement Goals List
- Profile Image

### Important Notes:
- Ensure your newly removed employee hasn't disrupted the functionality/information of any existing employee
- Make sure the employee's profile picture & modal-launch button is removed
- Make sure the employee's Bootstrap modal is removed

**Comment by renkesn** [comment]
Hey @SudiptiSharma could you please remove Patricia's profile from the UNLV-FIA website tomorrow? 

Thanks!

**Comment by Kelvyn-Meyers** [comment]
Confirming the profile has been removed:
![image](https://user-images.githubusercontent.com/72825162/206797520-536d3c1c-d1c8-43cb-98bb-f9b7e7de2a60.png)

**QA-CERTIFIED**
