### ISSUE TITLE
Add Alana Bayless to UNLV-FIA Team page

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#112]
This employee needs to be added to the UNLV-FIA Team Page. You can base your changes on existing employee profiles.

### Employee Information:
- Name: Alana Bayless
- Job Description: Student Web Accessibility Tester
- Room Number: [insert room number or skip if not applicable]
- Phone Number: [insert phone number or skip if not applicable]
- Email: alana.bayless@unlv.edu
- Biography: Alana Bayless joined the UNLV-FIA group as a student intern in January 2023. She is pursuing a Bachelor's of Arts Degree in Psychology and hopes to graduate in the Fall of 2023. Alana's post graduation plan is to pursue a Clinical Master's in Social Work. She mainly assists on the DATIM project ensuring that Section 508 standards are met throughout the site. In Alana's free time she enjoys watching movies/TV series, sewing, painting, drawing and exploring various other creative craft projects.
- Proficient Skills List: [insert a few languages/frameworks/etc. or skip if not applicable]
- Improvement Goals List: [insert a few languages/frameworks/etc. or skip if not applicable]
- Image: 
![Alana Bayless Headshot](https://user-images.githubusercontent.com/65931068/210829367-5a00b45e-1d23-4efa-9c16-7ff451e6bb81.jpg)

### Important Notes:
- Ensure the new employee is added alphabetically to the list (leave Brenda & Gretchen as the first two no matter what)
- Ensure newly added images are similar in size (200x200) or that they are cropped/expanded evenly to fit size requirements
- Ensure newly added divs, buttons, dialogs, etc. are given unique IDs (if an ID was necessary for that element)
- Ensure your newly added employee hasn't disrupted the functionality/information of any existing employee

**Comment by renkesn** [comment]
Hi @FoxAlexC , can you please add Alana to the UNLV-FIA website? Thanks!

**Comment by Kelvyn-Meyers** [comment]
Hi @renkesn, this issue should now be ready for QA. Thank you!

**Comment by renkesn** [comment]
Confirmed that Alan's profile was there and looks good! Closing issue
