### ISSUE TITLE
Update Dave Lorenz Castillo's profile

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#113]
This existing employee profile needs to be updated with the information below.

Employee Name: Dave Lorenz Castillo

### Information to Update:
- Job Description: Replace "[student programmer]" with "[software engineer]"
- Biography: @davecast-unlv please update your bio to reflect your new job, new projects you work on, and your graduation.
- Proficient Skills List: Replace "[previous value]" with "[new value]" (if not applicable, remove line)
- Improvement Goals List: Replace "[previous value]" with "[new value]" (if not applicable, remove line)

### Important Notes:
- Ensure the new employee is added alphabetically to the list (leave Brenda & Gretchen as the first two no matter what)
- Ensure newly added images are similar in size (200x200) or that they are cropped/expanded evenly to fit size requirements
- Ensure newly added divs, buttons, dialogs, etc. are given unique IDs (if an ID was necessary for that element)
- Ensure your updated employee profile hasn't disrupted the functionality/information of any existing employee

**Comment by Kelvyn-Meyers** [comment]
Hi @renkesn,

Dave's changes have been deployed and are ready for QA testing.

**Comment by renkesn** [comment]
QA Certified
