### ISSUE TITLE
Update Sudipti Sharma Profile

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#114]
This existing employee profile needs to be updated with the information below.

Employee Name: Sudipti Sharma

### Information to Update:
- Job Description: Replace "[student programmer]" with "[software engineer]"
- Biography: @SudiptiSharma please update your bio to reflect your new job, new projects you work on, and your graduation.
- Proficient Skills List: please update as necessary
- Improvement Goals List: Please update as necessary 

### Important Notes:
- Ensure the new employee is added alphabetically to the list (leave Brenda & Gretchen as the first two no matter what)
- Ensure newly added images are similar in size (200x200) or that they are cropped/expanded evenly to fit size requirements
- Ensure newly added divs, buttons, dialogs, etc. are given unique IDs (if an ID was necessary for that element)
- Ensure your updated employee profile hasn't disrupted the functionality/information of any existing employee

**Comment by Kelvyn-Meyers** [comment]
Hi @renkesn,

Sudipti's changes have been deployed and are now ready for QA testing.
