### ISSUE TITLE
Update Brenda Bucks Bio

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#116]
This existing employee profile needs to be updated with the information below.

Employee Name: Brenda Buck

### Information to Update:

- Biography: Brenda received her PHD in 1996, not 1966. Please change accordingly. 

Thanks!

### Important Notes:
- Ensure the new employee is added alphabetically to the list (leave Brenda & Gretchen as the first two no matter what)
- Ensure newly added images are similar in size (200x200) or that they are cropped/expanded evenly to fit size requirements
- Ensure newly added divs, buttons, dialogs, etc. are given unique IDs (if an ID was necessary for that element)
- Ensure your updated employee profile hasn't disrupted the functionality/information of any existing employee

**Comment by renkesn** [comment]
Hey @FoxAlexC ! When you have time can you make this quick change to Brenda's bio? The date she received her PhD is wrong in her Bio. Thanks!

**Comment by Kelvyn-Meyers** [comment]
Confirming date has been changed to 1996:
![image](https://user-images.githubusercontent.com/72825162/211087058-0680a3f0-c43c-4891-b180-c08f30ae6bab.png)

**QA-CERTIFIED**

**Comment by renkesn** [comment]
Thank you @FoxAlexC  and @Kelvyn-Meyers !!
