### ISSUE TITLE
Add Michelle McGowan Profile to our Webpage

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#119]
This employee needs to be added to the UNLV-FIA Team Page. You can base your changes on existing employee profiles.

### Employee Information:
- Name: Michelle McGowan
- Job Description: [insert job title]: Student Programmer
- Work Location: Remote
- Phone Number: [insert phone number or skip if not applicable]
- Email: [insert UNLV staff email]
- Biography: [write and insert a biography]
- Proficient Skills List: [insert a few languages/frameworks/etc]
- Improvement Goals List: [insert a few languages/frameworks/etc.]
- Image: [insert a link to a 200x200 image hosted externally if possible (ex: imgur.com)]

### Important Notes:
- Ensure the new employee is added alphabetically to the list (leave Brenda & Gretchen as the first two no matter what)
- Ensure newly added images are similar in size (200x200) or that they are cropped/expanded evenly to fit size requirements
- Ensure newly added divs, buttons, dialogs, etc. are given unique IDs (if an ID was necessary for that element)
- Ensure your newly added employee hasn't disrupted the functionality/information of any existing employee

**Comment by Kelvyn-Meyers** [comment]
Hi @renkesn,

Michelle's profile has now been deployed. Whenever you get the chance, this issue can be QA'd. Thank you!
