### ISSUE TITLE
Update Pankey's Profile 

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#127]
This existing employee profile needs to be updated with the information below.

Employee Name: Brian Pankey

### Information to Update:
- Biography: Update bio to the following: Brian Pankey has worked as a Computer Systems Analyst with the UNLV-FIA group since May 2003. He received a B.S. in Agricultural Science from the University of Illinois and earned an additional Computer Career Certificate. Brian is a key contributor to several FIA projects including, Maestro, TPO, and EVALIDator. In his spare time, Brian enjoys gardening, stained glass, and building/restoring motorcycles.

### Important Notes:
- Ensure the new employee is added alphabetically to the list (leave Brenda & Gretchen as the first two no matter what)
- Ensure newly added images are similar in size (200x200) or that they are cropped/expanded evenly to fit size requirements
- Ensure newly added divs, buttons, dialogs, etc. are given unique IDs (if an ID was necessary for that element)
- Ensure your updated employee profile hasn't disrupted the functionality/information of any existing employee

**Comment by Kelvyn-Meyers** [comment]
Hi @renkesn,

Brandon's changes to Brian's profile have been deployed, so this issue is ready for QA. Thank you!
