### ISSUE TITLE
Update Natalie's Profile

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#128]
This existing employee profile needs to be updated with the information below.

Employee Name: Natalie Renkes

### Information to Update:
- Job Description: Project Manager
- Biography: Update to: Natalie Renkes joined the UNLV-FIA group in May 2020. She anticipates receiving her M.S. degree in Geoscience from UNLV in the spring of 2023. She supervises student interns/ staff members, is project manager for the DATIM and EVALIDator projects, and performs other duties based on FIA National Operations priorities. As a member of the FIA Section 508 Program Development Team, she is also working to ensure our group's compliance with federal accessibility laws. Outside of UNLV-FIA, Natalie’s research interests focus on naturally-occurring asbestos and its health implications within metropolitan Las Vegas. In her spare time, Natalie enjoys playing The Legend of Zelda: Breath of the Wild, hiking/camping, and is an avid reader. Her favorite book series is Game of Thrones (she hasn’t seen the show, don’t ruin the ending)!
- Proficient Skills List: Section 508 Web Accessibly Testing, Student Management, Junior Project Management 
- Improvement Goals List: Staff Management and Project Management 

### Important Notes:
- Ensure the new employee is added alphabetically to the list (leave Brenda & Gretchen as the first two no matter what)
- Ensure newly added images are similar in size (200x200) or that they are cropped/expanded evenly to fit size requirements
- Ensure newly added divs, buttons, dialogs, etc. are given unique IDs (if an ID was necessary for that element)
- Ensure your updated employee profile hasn't disrupted the functionality/information of any existing employee

**Comment by Kelvyn-Meyers** [comment]
Hi @renkesn,

Your profile has been updated by Michelle and is now ready for QA testing. Thank you!

**Comment by davecast-unlv** [comment]
Hi @renkesn,

Michelle has updated your profile and is ready for QA testing. Thanks!

**Comment by AlanaBayless** [comment]
Natalie's description in the UNLV-FIA Team page reflects the changes requested above.
