### ISSUE TITLE
Update Kelvyn's Profile

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#129]
This existing employee profile needs to be updated with the information below.

Employee Name: Kelvyn Meyers

### Information to Update:
- Biography: Replace with the following: Kelvyn Meyers originally joined the UNLV-FIA group as a student intern in October 2020. He received his Bachelor of Science Degree in Computer Science from the University of Nevada, Las Vegas (UNLV) in May 2021. Kelvyn is now a software engineer on the DATIM project and assists student interns in ensuring 508 standards are upheld across the site. In his free time, he enjoys working on personal projects, playing video games, and spending time with his family.
- Proficient Skills: Replace with the following: .NET Framework, ArcGIS Development, C#, Python, Java, Lua, HTML/CSS/JS, jQuery
- Improvement Goals: Replace with the following: React, Angular, Node.js, WPF, Database Development

### Important Notes:
- Ensure the new employee is added alphabetically to the list (leave Brenda & Gretchen as the first two no matter what)
- Ensure newly added images are similar in size (200x200) or that they are cropped/expanded evenly to fit size requirements
- Ensure newly added divs, buttons, dialogs, etc. are given unique IDs (if an ID was necessary for that element)
- Ensure your updated employee profile hasn't disrupted the functionality/information of any existing employee

**Comment by Kelvyn-Meyers** [comment]
Since this is my profile, I'll QA this. Everything looks good!
