### ISSUE TITLE
Update Kevin Luk's Profile

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#130]
This existing employee profile needs to be updated with the information below.

Employee Name: Kevin Luk

### Information to Update:

- Biography: Replace with: Kevin joined the UNLV-FIA group in October 2021. He has a Bachelor of Science degree in Biology, and is currently pursuing a second Bachelor of Science Degree in Computer Science at Oregon State University. Kevin works as a software engineer on the DATIM and EVALIDator Projects. In his free time, his hobbies include weightlifting and singing.

### Important Notes:
- Ensure the new employee is added alphabetically to the list (leave Brenda & Gretchen as the first two no matter what)
- Ensure newly added images are similar in size (200x200) or that they are cropped/expanded evenly to fit size requirements
- Ensure newly added divs, buttons, dialogs, etc. are given unique IDs (if an ID was necessary for that element)
- Ensure your updated employee profile hasn't disrupted the functionality/information of any existing employee

**Comment by Kelvyn-Meyers** [comment]
Hi @renkesn,

Kevin's profile has been updated by Michelle and is now ready for QA testing. Thank you!
