### ISSUE TITLE
Update Ron Waneks Profile

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#132]
This existing employee profile needs to be updated with the information below.

Employee Name: Ron Wanek

### Information to Update:
- Improvement Goals List: remove line
- Image: Natalie emailed Ron on 1/27/23 asking for a new picture. 

### Important Notes:
- Ensure the new employee is added alphabetically to the list (leave Brenda & Gretchen as the first two no matter what)
- Ensure newly added images are similar in size (200x200) or that they are cropped/expanded evenly to fit size requirements
- Ensure newly added divs, buttons, dialogs, etc. are given unique IDs (if an ID was necessary for that element)
- Ensure your updated employee profile hasn't disrupted the functionality/information of any existing employee

**Comment by Kelvyn-Meyers** [comment]
Keeping this issue under "In Progress" until we get Ron's new image. Though his unused Improvement Goals were removed with PR #135.

**Comment by renkesn** [comment]
Hi @michellemcgowan , please update Ron's profile picture and copy and paste the following into his bio. Thanks!

"Ron Wanek has worked for the Forest Service for over 35 years and 20 years as a FIA employee. Following his retirement from the Forest Service, he joined the UNLV-FIA group as a Data Specialist in 2018. Ron has been an important part of our team and provides subject matter expertise on the design and development support of FIA information management systems in areas such as: data warehouse design, data extractions, transformations, and loads (ETLs), data processing, database programming, data analytics, database administration, software architecture, and quality assurance testing. Ron received a B.S. in Forest Management from Oregon State University."



![Image](https://user-images.githubusercontent.com/65931068/217375621-57b9d7c3-dd30-44de-8dfd-1b7e202ff7c5.jpg)

**Comment by davecast-unlv** [comment]
Hi @renkesn,

Ron's profile has been updated by Michelle. Should be good to go for QA testing. Thank you!

**Comment by AlanaBayless** [comment]
On the UNLV-FIA Team page, Ron's description, profile picture and skills section was updated to reflect the changes requested above.
