### ISSUE TITLE
Update contact information

### ISSUE THREAD

**Issue by gmandrew-unlv** [UNLV-FIA/UNLV-FIA-Group#141]
The bottom of the webpage gives contact information. It currently includes Gretchen's email address, her old office phone number, and the Geoscience fax number. The issue is that that phone number is now wrong (but we don't want personal cell numbers published). 

**Approved solution:** Delete the phone number and fax number from the contact information.

![Image](https://user-images.githubusercontent.com/38762544/223518054-5d53c2e8-37ee-4f9f-9f42-8751e882826b.png)

**Comment by gmandrew-unlv** [comment]
Hi @FoxAlexC. This issue is approved for implementation & assigned to you. Let Natalie or me know if you have any questions. Thanks!

**Comment by Kelvyn-Meyers** [comment]
@FoxAlexC's PR has been merged and this issue is now ready for QA.

**Comment by renkesn** [comment]
Gretchen's contact information has been updated to only reflected her email. I checked to make sure her email was at the bottom for all pages within the website. QA certified 

![image](https://user-images.githubusercontent.com/65931068/223865303-b444bb21-b76e-43a6-9f5f-83e29d3ef481.png)
