### ISSUE TITLE
Add New Employee Angela Gruenenfelder

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#143]
This employee needs to be added to the UNLV-FIA Team Page. You can base your changes on existing employee profiles.

### Employee Information:
- Name: Angie Gruenenfelder
- Job Description: UNLV-FIA Program Manager
- Room Number: [insert room number or skip if not applicable]
- Phone Number: [insert phone number or skip if not applicable]
- Email: angela.gruenenfelder@unlv.edu
- Biography: Angie Gruenenfelder has worked with the UNLV-FIA since April 2023. Angie currently serves as Program Manager and provides program management support for the cooperative agreement between UNLV and the USDA Forest Service.  She monitors the group's contributions and deliverables, supervises our staff, and oversees much of our daily operations. Angie received her B.S. in Kinesiology from the University of Nevada, Las Vegas (UNLV). In her personal time, she enjoys spending her time outdoors, golfing, hiking, camping, and reading.
- Proficient Skills List: Project Management, Staff Management, Academic Research, Writing
- Improvement Goals List: {skip if not applicable]
- Image: 
![Angie2](https://github.com/UNLV-FIA/UNLV-FIA-Group/assets/132308256/4e7dc4f9-4466-4b32-b28a-11cd0fc4f871)

### Important Notes:
- Ensure the new employee is added alphabetically to the list (leave Brenda & Gretchen as the first two no matter what)
- Ensure newly added images are similar in size (200x200) or that they are cropped/expanded evenly to fit size requirements
- Ensure newly added divs, buttons, dialogs, etc. are given unique IDs (if an ID was necessary for that element)
- Ensure your newly added employee hasn't disrupted the functionality/information of any existing employee

**Comment by agruenenfelder-unlv** [comment]
@bae-junghwan Hi Brandon!  I apologize for the delay in getting this information updated, but it should be ready to go.  Please let me know if you have any questions.  Thanks!
