### ISSUE TITLE
Remove Kevin Luk's Profile

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#147]
This employee needs to be Removed from the UNLV-FIA Team Page. 

Employee Name: Kevin Luk. Last day is April 26. 

### Employee Information to Remove:
- Name
- Job Description
- Room Number
- Phone Number
- Email
- Biography
- Proficient Skills List
- Improvement Goals List
- Profile Image

### Important Notes:
- Ensure your newly removed employee hasn't disrupted the functionality/information of any existing employee
- Make sure the employee's profile picture & modal-launch button is removed
- Make sure the employee's Bootstrap modal is removed

**Comment by agruenenfelder-unlv** [comment]
@michellemcgowan Hey Michelle, it's Angie.  I wanted to let you know that Kevin's last day was April 26th and I have updated the  date in the description above.  No need to wait until 5/19, you can go ahead and implement this now if you would like.  Thanks!

**Comment by michellemcgowan** [comment]
@agruenenfelder-unlv Kevin's profile has been removed! :)

**Comment by agruenenfelder-unlv** [comment]
@Michelle McGowan ***@***.***> you are the best!  Thank you!
