### ISSUE TITLE
Update Alex's Profile

### ISSUE THREAD

**Issue by FoxAlexC** [UNLV-FIA/UNLV-FIA-Group#159]
This existing employee profile needs to be updated with the information below.

Employee Name: Alex Fox

### Information to Update:
- Job Description: Replace "Student Programmer" with "Software Engineer"
- Biography: Replace Pre-Grad Information with Post-Grad Information 
- Proficient Skills List: Update with new skills
- Improvement Goals List: Update with new skills

### Important Notes:
- Ensure the new employee is added alphabetically to the list (leave Brenda & Gretchen as the first two no matter what)
- Ensure newly added images are similar in size (200x200) or that they are cropped/expanded evenly to fit size requirements
- Ensure newly added divs, buttons, dialogs, etc. are given unique IDs (if an ID was necessary for that element)
- Ensure your updated employee profile hasn't disrupted the functionality/information of any existing employee

**Comment by agruenenfelder-unlv** [comment]
Issue has been QA'd and the information requested in the ticket is correct.
