### ISSUE TITLE
Add New Employee: Vicki Foster 

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#168]
This employee needs to be added to the UNLV-FIA Team Page. You can base your changes on existing employee profiles.

### Employee Information:
- Name: Vicki Foster
- Job Description: Subject Matter Expert/Data Specialist
- Phone Number: [insert phone number or skip if not applicable]
- Email: vicki.foster@unlv.edu
- Biography:  Vicki Foster worked as a Forest Service employee for 8 years and also worked with the United States Air Force both active duty and as a civilian employee. Following her retirement from the Forest Service, she joined the UNLV-FIA group as a Subject Matter Expert & Data Specialist in June 2023. She has extensive experience in database management and has been an important contributor to the MIDAS, NOMS, and NIMS projects. Vicki received her M.S. in Management/Management Information Systems from Minot State University and enjoys riding motorcycles, kayaking, camping, and exploring the forests and beaches of Alaska.
Proficient Skills    Database Management, Maintenance & Support, Access, Visual Basic, SQL, Oracle

- Image:  
![Vicki Foster Photo](https://github.com/UNLV-FIA/UNLV-FIA-Group/assets/132308256/c677e973-470b-4aa0-8502-bcb84f8e0705)

### Important Notes:
- Ensure the new employee is added alphabetically to the list (leave Brenda & Gretchen as the first two no matter what)
- Ensure newly added images are similar in size (200x200) or that they are cropped/expanded evenly to fit size requirements
- Ensure newly added divs, buttons, dialogs, etc. are given unique IDs (if an ID was necessary for that element)
- Ensure your newly added employee hasn't disrupted the functionality/information of any existing employee

**Comment by renkesn** [comment]
@agruenenfelder-unlv I created this new issue to add vicki Foster to our Github page. We need to edit the issue to add in the missing info.

**Comment by agruenenfelder-unlv** [comment]
@bae-junghwan Hi Brandon I've assigned this task to you.  If you would please have this completed by Friday, June 23rd I would greatly appreciate.  Let me know if you have any questions.  Thank you!!

**Comment by Kelvyn-Meyers** [comment]
Hi @agruenenfelder-unlv,

@bae-junghwan added Vicki's profile & picture a couple of days ago, so you should be able to cross it off your TODO list. You can take a look at it here: https://unlv-fia.github.io/UNLV-FIA-Group/TeamPage.html

This also applies to your new profile & picture for this issue: https://github.com/UNLV-FIA/UNLV-FIA-Group/issues/143

Let us know if you have any questions or want to request changes to either profile. Thank you!

**Comment by agruenenfelder-unlv** [comment]
@Kelvyn-Meyers @bae-junghwan 
You guys are amazing!  

Thank you and I hope you both have a wonderful weekend! :)
