### ISSUE TITLE
Update Gretchen's profile

### ISSUE THREAD

**Issue by gmandrew-unlv** [UNLV-FIA/UNLV-FIA-Group#171]
Please update my profile on the Team page as follows:

Gretchen Andrew - Program Manager, Forest Inventory and Analysis
Work Location: Remote
Email: gretchen.andrew@unlv.edu

Gretchen Andrew has worked with the UNLV-FIA group since 2009. She currently serves as Program Manager for UNLV-FIA and UNIMS. She also works closely with the FIA National Operations team to improve project management and change management practices and processes. She serves as functional manager for UNLV staff and oversees much of our daily operations. She continually strives to find solutions and strategies to ensure our long-term success. Gretchen received her M.S. in Environmental Science from the University of Nevada, Las Vegas (UNLV). In her personal time, she enjoys hiking, camping, and reading.

Proficient Skills: Program/Project Management, Staff Management, Academic Research & Studies, Writing

Improvement Goals [delete]

**Comment by gmandrew-unlv** [comment]
Hi @bae-junghwan. Just letting you know I assigned you this new ticket. Thanks!

**Comment by agruenenfelder-unlv** [comment]
Hey @bae-junghwan! No worries at all.  Thanks so much for all you do! :)
