### ISSUE TITLE
Update John Bertini's Title

### ISSUE THREAD

**Issue by agruenenfelder-unlv** [UNLV-FIA/UNLV-FIA-Group#174]
This existing employee profile needs to be updated with the information below.

Employee Name: John Bertini

### Information to Update:
- Job Description: Update title to Senior Software Engineer

### Important Notes:
- Ensure the new employee is added alphabetically to the list (leave Brenda & Gretchen as the first two no matter what)
- Ensure newly added images are similar in size (200x200) or that they are cropped/expanded evenly to fit size requirements
- Ensure newly added divs, buttons, dialogs, etc. are given unique IDs (if an ID was necessary for that element)
- Ensure your updated employee profile hasn't disrupted the functionality/information of any existing employee

**Comment by agruenenfelder-unlv** [comment]
@bae-junghwan Hi Brandon!  Just letting you know that I assigned this additional task to you.

**Comment by bae-junghwan** [comment]
Hi @agruenenfelder-unlv, got the update merged in, should be ready to test. Thank you!

**Comment by agruenenfelder-unlv** [comment]
Thank you @bae-junghwan! I appreciate your work on this.
