### ISSUE TITLE
Remove BP from Website

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#177]
This employee needs to be Removed from the UNLV-FIA Team Page. 

Employee Name: Brian Pankey.

### Employee Information to Remove:
- Name
- Job Description
- Room Number
- Phone Number
- Email
- Biography
- Proficient Skills List
- Improvement Goals List
- Profile Image

### Important Notes:
- Ensure your newly removed employee hasn't disrupted the functionality/information of any existing employee
- Make sure the employee's profile picture & modal-launch button is removed
- Make sure the employee's Bootstrap modal is removed

**Comment by bae-junghwan** [comment]
Hi @renkesn! The PR for this issue has been merged and is ready for QA!

**Comment by agruenenfelder-unlv** [comment]
Issue has been QA'd and the information requested in the ticket is correct.
