### ISSUE TITLE
Add New Projects to UNLV-FIA Website

### ISSUE THREAD

**Issue by agruenenfelder-unlv** [UNLV-FIA/UNLV-FIA-Group#181]
Please add the following projects to the Projects page of the UNLV-FIA website:

**Acronym:** Sample Nonresponse Bias in Estimations
**Project Name:**	Sample Nonresponse Bias in Estimations 
**Description:**  The SNBE project evaluates estimation methods for handling field plot nonresponse.  Further investigation and evaluations are being conducted to determine what other methods may be tenable to address biases more adequately in the samples that result from nonrandom nonresponse.

**Acronym:** FIA National Science Strategy
**Project Name:**	FIA National Science Strategy
**Description:**  The goal of the FIA National Science Strategy project is to create a coordinated vision and strategy to support and improve on creativity, collaboration, and initiative among the FIA research staff, individually and collectively.  In turn, we hope to discover programmatic mechanisms that will bridge scientific inquiry to ongoing inventory operations.

**Acronym:** EVALIDator
**Project Name:**	EVALIDator
**Description:**  This public facing web analytical tool allows users to produce a large variety of population estimates and their sampling errors based on the current Forest Inventory and Analysis Database (FIADB).

Please let me know if you have any questions.  Thank you!
Angie

**Comment by agruenenfelder-unlv** [comment]
Good Morning @bae-junghwan!  Wanted to give you a heads up that I assigned this issue to you.  Please let me know if you have any questions or need additional information from me.  Thanks & Happy Friday! :)

**Comment by bae-junghwan** [comment]
Hi @agruenenfelder-unlv! Wanted to let you know that I got the PR in for it and it has been merged. This issue is now ready for QA!

**Comment by agruenenfelder-unlv** [comment]
Hi @bae-junghwan!  The issue has been QA'd and looks great!  Thank you!
