### ISSUE TITLE
Update UMaestro project description

### ISSUE THREAD

**Issue by gmandrew-unlv** [UNLV-FIA/UNLV-FIA-Group#183]
On the Projects page, we need to update the entry on UMaestro as follows:
1. Acronym column: change from "uMaestro" to **UMaestro**
2. Project Name column: change from "Urban Maestro ("uMaestro")" to **Universal Maestro (UMaestro)**
3. Description column: change description as follows: "Universal Maestro (UMaestro) is a web tool used for data management to upload post-field processes and quality assured data to the UNIMS database."

**Comment by gmandrew-unlv** [comment]
Hi @bae-junghwan. Just a heads up that I created this new issue and assigned it to you. Let me know if you have any questions.

**Comment by bae-junghwan** [comment]
Hi @gmandrew-unlv, issue has been resolved and successfully merged!

**Comment by gmandrew-unlv** [comment]
Thanks @bae-junghwan!
