### ISSUE TITLE
Update Alana Bayless' Job Description and Web Profile

### ISSUE THREAD

**Issue by agruenenfelder-unlv** [UNLV-FIA/UNLV-FIA-Group#187]
This existing employee profile needs to be updated with the information below.

Employee Name: Alana Bayless

### Information to Update:
- Job Description: Replace "Student Web Accessibility Tester" with "Program Coordinator" 

- Biography: **REPLACE** "Alana Bayless joined the UNLV-FIA group as a student intern in January 2023. She is pursuing a Bachelor's of Arts Degree in Psychology and hopes to graduate in the Fall of 2023. Alana's post graduation plan is to pursue a Clinical Master's in Social Work. She mainly assists on the DATIM project ensuring that Section 508 standards are met throughout the site. In Alana's free time she enjoys watching movies/TV series, sewing, painting, drawing and exploring various other creative craft projects." **WITH** "Alana Bayless joined the UNLV-FIA group as a student intern in January 2023, and now serves as a Program Coordinator. Certified as a Trusted Tester by the Department of Homeland Security, Alana assesses web content to determine conformance to Section 508 and Web Content Accessibility Guidelines (WCAG). She also performs quality assurance/quality control testing on the DATIM project. Alana received her Bachelor of Arts degree in Psychology from the UNLV in August 2023, and plans to pursue a Clinical Master's in Social Work. In her free time, Alana enjoys watching movies/TV series, sewing, painting, drawing, and other creative craft projects." 

### Important Notes:
- Ensure the new employee is added alphabetically to the list (leave Brenda & Gretchen as the first two no matter what)
- Ensure newly added images are similar in size (200x200) or that they are cropped/expanded evenly to fit size requirements
- Ensure newly added divs, buttons, dialogs, etc. are given unique IDs (if an ID was necessary for that element)
- Ensure your updated employee profile hasn't disrupted the functionality/information of any existing employee

**Comment by agruenenfelder-unlv** [comment]
Hi @michellemcgowan!  I wanted to give you a heads-up to let you know that I assigned this task to you.  Hope you're having a wonderful day! :)

**Comment by michellemcgowan** [comment]
Sounds good! Thank you, you too!  <]:))))

**Comment by michellemcgowan** [comment]
@agruenenfelder-unlv hope you are having a good day! This issue has been completed and merged. :)

**Comment by agruenenfelder-unlv** [comment]
Thank you @michellemcgowan for the quick turnaround!  You're amazing! :)
