### ISSUE TITLE
Remove Jung Brandon Bae from UNLV-FIA Team Page

### ISSUE THREAD

**Issue by AlanaBayless** [UNLV-FIA/UNLV-FIA-Group#189]
This employee needs to be Removed from the UNLV-FIA Team Page. 

Employee Name: [insert employee name here].

### Employee Information to Remove:
- Name: Jung Brandon Bae
- Job Description: Student Programmer
- Room Number
- Phone Number
- Email
- Biography
- Proficient Skills List
- Improvement Goals List
- Profile Image

### Important Notes:
- Ensure your newly removed employee hasn't disrupted the functionality/information of any existing employee
- Make sure the employee's profile picture & modal-launch button is removed
- Make sure the employee's Bootstrap modal is removed

**Comment by agruenenfelder-unlv** [comment]
Good Morning @michellemcgowan!  I wanted to give you a heads up that this issue has been assigned to you.  Have a great day!

**Comment by michellemcgowan** [comment]
@agruenenfelder-unlv, this issue has been completed and merged. so sad you are leaving :((
