### ISSUE TITLE
Remove Angie Gruenenfelder from UNLV-FIA Team Page 

### ISSUE THREAD

**Issue by agruenenfelder-unlv** [UNLV-FIA/UNLV-FIA-Group#190]
This employee needs to be Removed from the UNLV-FIA Team Page:  EFFECTIVE DATE 10/1/2023

Employee Name: Angie Gruenenfelder

### Employee Information to Remove:
- Name
- Job Description
- Room Number
- Phone Number
- Email
- Biography
- Proficient Skills List
- Improvement Goals List
- Profile Image

### Important Notes:
- Ensure your newly removed employee hasn't disrupted the functionality/information of any existing employee
- Make sure the employee's profile picture & modal-launch button is removed
- Make sure the employee's Bootstrap modal is removed

**Comment by agruenenfelder-unlv** [comment]
Good morning @michellemcgowan!  Just giving you a heads up that this issue has been assigned to you. :(  Please note my profile should be removed effective 10/1/23.  Thanks so much Michelle! :)

**Comment by gmandrew-unlv** [comment]
Hi @michellemcgowan. Just a reminder that Angie's profile needs to be removed from our website. I notice that you responded to Angie's earlier comment with a confused emoji. Do you have questions about this? Let me know if you need help and I'll do my best to point you in the right direction with @renkesn out sick. Thanks!

**Comment by michellemcgowan** [comment]
@gmandrew-unlv sorry i didn't know it was a confused emoji i meant sad face! But thank you for the reminder!

**Comment by gmandrew-unlv** [comment]
@michellemcgowan LOL! That gave me a good laugh. It DOES look like a sad face!
