### ISSUE TITLE
Add EVALIDator Project to  Alex Fox's Bio 

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#193]
This existing employee profile needs to be updated with the information below.

Employee Name: Alexander Fox

### Information to Update:

- Biography: Replace bio on website with the paragraph below. 
Alex Fox joined the UNLV-FIA group as a student intern in September 2021. He received his Bachelor of Science Degree in Computer Science from the University of Nevada, Las Vegas (UNLV) in May 2023. He is now a software engineer on the DATIM and EVALIDator projects. In Alex's free time he enjoys watching sports, playing video games with his friends, and working on his own personal coding projects.

### Important Notes:
- Ensure the new employee is added alphabetically to the list (leave Brenda & Gretchen as the first two no matter what)
- Ensure newly added images are similar in size (200x200) or that they are cropped/expanded evenly to fit size requirements
- Ensure newly added divs, buttons, dialogs, etc. are given unique IDs (if an ID was necessary for that element)
- Ensure your updated employee profile hasn't disrupted the functionality/information of any existing employee

**Comment by renkesn** [comment]
Hi @michellemcgowan, can you please update Alex Fox's profile by 10/27/23.

**Comment by michellemcgowan** [comment]
@renkesn issue has been approved and merged! ready for QA
