### ISSUE TITLE
Add FIA Spatial Database as a Project

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#195]
Please add the following project to the Projects page of the UNLV-FIA website:

**Acronym:** FIA Spatial Database
**Project Name:** FIA Spatial Database 
**Description:** Assist in maintaining the spatial data related to FIA inventory.

**Comment by renkesn** [comment]
Hi @michellemcgowan , can you please add this project to our website by 11/1/23?

Thanks!

**Comment by michellemcgowan** [comment]
@renkesn this issue has been approved and merged through PR #197  !
