### ISSUE TITLE
Update Dr. Brenda Buck's Profile Pic/ Bio

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#203]
This existing employee profile needs to be updated with the information below.

Employee Name: [insert existing employee's full name] 

### Information to Update:
- Biography:

Dr. Brenda J. Buck has been with the UNLV-FIA since 2017. As the Program Director and Principal Investigator, she works to provide oversight for our daily operations.

Dr. Buck received her Ph.D. in 1996 from New Mexico State University in Agronomy/Soil Science. She has been a professor at UNLV since 1998. Dr. Buck’s research has spanned a wide range of interdisciplinary topics including: Medical geology research on health hazards associated with dust exposure including those from naturally-occurring asbestos minerals, arsenic, and other carcinogens. Earlier work included research on warm deserts: soil genesis, radionuclide and heavy metal contamination, biologic soil crusts, paleoclimate & landscape evolution, salt tectonics, geomorphic hazards, and other applications of arid soil science/geology. Dr. Buck has served as a researcher, collaborator, and teacher for field expeditions to 18 countries on 6 continents. She is also an artist, outdoor enthusiast, cyclist, and loves live music!

- Image: Replace with the following image:
<img width="340" alt="BrendaBuck jpg" src="https://github.com/UNLV-FIA/UNLV-FIA-Group/assets/65931068/9bfab27d-3059-4153-bef5-7f7eeef2ff4c">

### Important Notes:
- Ensure the new employee is added alphabetically to the list (leave Brenda & Gretchen as the first two no matter what)
- Ensure newly added images are similar in size (200x200) or that they are cropped/expanded evenly to fit size requirements
- Ensure newly added divs, buttons, dialogs, etc. are given unique IDs (if an ID was necessary for that element)
- Ensure your updated employee profile hasn't disrupted the functionality/information of any existing employee

**Comment by michellemcgowan** [comment]
@renkesn this issue has been addressed and is ready for QA!
