### ISSUE TITLE
Divide Projects List into Active and Past Projects

### ISSUE THREAD

**Issue by michellemcgowan** [UNLV-FIA/UNLV-FIA-Group#205]
Make two tables based on if UNLV-FIA is still working on them or not. If project not already on the website, no need to add. 

List of Projects that are we are working on: 
![image](https://github.com/UNLV-FIA/UNLV-FIA-Group/assets/123202350/e8f508f3-77da-41a2-90e4-4472ad629905)

**Comment by michellemcgowan** [comment]
@renkesn this issue has been addressed and is ready for QA!

**Comment by renkesn** [comment]
FIA Datamart needs added to this list. see description below: The FIA DataMart allows visitors to download raw FIA data in comma delimited tables, SQLite databases, and customizable batch estimate workbooks. The DataMart map also provides a quick visual reference for the most recent data available for each state or inventory area.

@michellemcgowan
