### ISSUE TITLE
Update Joe Tschida's Bio

### ISSUE THREAD

**Issue by gmandrew-unlv** [UNLV-FIA/UNLV-FIA-Group#233]
Joe has asked that the first sentence of his bio be deleted so that it doesn't attract unwanted attention from his former employer. I've made additional minor tweaks for better readability. The full paragraph should read as follows:

Joe Tschida joined the UNLV-FIA group as a full-time Enterprise Data Architect on January 1, 2024. Having been in the industry since 1990, Joe brings decades of experience to the team. He builds data platforms, employs data integration techniques, and tools with all kinds of data projects. He seeks to leverage his skills as a data architect, modeler, developer, and analyst to assist FIA with enterprise efficiency and lean capabilities. He also hopes to promote strategic and operational improvements via enhanced insights and abilities to make decisions.

**Comment by gmandrew-unlv** [comment]
Hi @ballec6, can you implement this change? Let me know if you have any questions. Thanks!

**Comment by renkesn** [comment]
@michellemcgowan Joe's request on 4/3: could you just mention my start date as "early 2024" rather than 1/1?

**Comment by renkesn** [comment]
Hi @michellemcgowan can you please update the first sentence of Joe's profile to the following: 

"Joe Tschida joined the UNLV-FIA group as an Enterprise Data Architect in 2024."

Thanks Michelle! Please make this a priority for tomorrow.

**Comment by michellemcgowan** [comment]
@renkesn addressed and merged! Ready for QA!
