### ISSUE TITLE
Add Apollo Draco Profile to Website

### ISSUE THREAD

**Issue by AlanaBayless** [UNLV-FIA/UNLV-FIA-Group#252]
This employee needs to be added to the UNLV-FIA Team Page. You can base your changes on existing employee profiles.

### Employee Information:
- Name: Apollo Draco
- Job Description: Student Accessibility Tester
- Email: apollo.draco@unlv.edu
- Biography: Apollo joined the UNLV-FIA group as a student Web Accessibility Tester in June 2024. Apollo is working on earning his certification to become a Trusted Tester through the Department of Homeland Security and will be assessing web content with a goal to improve accessibility utilizing Section 508 and Web Content Accessibility Guidelines (WCAG) on DATIM. He is an Information Systems major, and has experience in System Administration. In his spare time, Apollo enjoys D&D, hiking, and reading fantasy novels.
- Image: ![Image](https://github.com/UNLV-FIA/UNLV-FIA-Group/assets/122119181/aad9744c-94d0-4cf7-b6d3-73c2d8f5fbff)

### Important Notes:
- Ensure the new employee is added alphabetically to the list (leave Brenda & Gretchen as the first two no matter what)
- Ensure newly added images are similar in size (200x200) or that they are cropped/expanded evenly to fit size requirements
- Ensure newly added divs, buttons, dialogs, etc. are given unique IDs (if an ID was necessary for that element)
- Ensure your newly added employee hasn't disrupted the functionality/information of any existing employee

**Comment by Kelvyn-Meyers** [comment]
Hi @AlanaBayless,

Is this ticket ready for implementation? If so, @ballec6 said he could handle it. Thanks!

**Comment by AlanaBayless** [comment]
@Kelvyn-Meyers I am still waiting on Apollo's bio. I will assign CJ as soon as I get Apollo's Bio.

**Comment by AlanaBayless** [comment]
Closing this ticket due to Apollo's resignation on 6/24/24.
