### ISSUE TITLE
1.3.1 Info and Relationships (A)

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#72]
### 1.3.1 Info and Relationships - Level A
Information, structure, and relationships conveyed through presentation can be programmatically determined or are available in text.

[Understanding 1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)
[How to Meet 1.3.1](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=133%2C131#info-and-relationships)
[How to Test 1.3.1, 5.C)](https://usfs.box.com/s/ef9cpv0aqlnmwovhql9sim7pri5hsscw)
[How to Test 1.3.1, 10.B-D)](https://usfs.box.com/s/enviootlzy2r43fiwjcrwskhe8uyfir7)
[How to Test 1.3.1, 14.A-C)](https://usfs.box.com/s/t8qe0lfd8luenxxxp3k84o85evpcwrlu)
[How to Test 1.3.1, 15.A)](https://usfs.box.com/s/21xrm512bq8inpgecjirklc02xt88q67)

**Trusted Tester IDs:**
- [x] Test 5.C programmatic-label
- [x] Test 10.B heading-determinable
- [x] Test 10.C heading-level
- [ ] Test 10.D list-type
- [x] Test 14.A table-identification
- [x] Test 14.B cell-header-association
- [x] Test 14.C layout-table-structure
- [x] Test 15.A meaningful-content-css-before-after

**Accessibility Principle:** Perceivable (Adaptable)

**Comment by AlanaBayless** [comment]
Overall, all three pages pass 1.3.1 Info and Relationships:
- [ ] Test 5.C programmatic-label: DNA, there are no form elements on the pages.
- [ ] Test 10.B heading-determinable: PASS, each visual heading is programmatically determinable on all pages.
- [ ] Test 10.C heading-level: PASS, Programmatic heading levels logically match the visual heading presentation.
- [ ] Test 10.D list-type: PASS, all visually apparent lists are identified on all pages.
- [ ] Test 14.A table-identification: PASS, all tables are identified on pages Team and Projects. There are no tables on the Home page.
- [ ] Test 14.B cell-header-association: PASS, All data cells are programmatically associated with relevant headers for both tables.
- [ ] Test 14.C layout-table-structure: DNA, there are no layout tables on the page.
- [ ] Test 15.A meaningful-content-css-before-after: DNA, no meaningful content was inserted using ::before or ::after.
