### ISSUE TITLE
2.4.4 Link Purpose (In Context) (A)

### ISSUE THREAD

**Issue by Kelvyn-Meyers** [UNLV-FIA/UNLV-FIA-Group#75]
### 2.4.4 Link Purpose (In Context) - Level A
The purpose of each link can be determined from the link text alone or from the link text together with its programmatically determined link context, except where the purpose of the link would be ambiguous to users in general.

[Understanding 2.4.4](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html)
[How to Meet 2.4.4](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=131%2C133%2C141%2C143%2C211%2C212%2C221%2C231%2C242%2C244#link-purpose-in-context)
[How to Test 2.4.4](https://usfs.box.com/s/kba7gsnp0e4vt20c2aw6tevimlh199ku)

**Trusted Tester ID:**
- [ ] Test 6.A link-purpose

**Accessibility Principle:** Operable (Navigable)

**Comment by AlanaBayless** [comment]
All three pages pass 2.4.4 Link Purpose, the purpose of each link can be determined from the link/button text alone or from the link/button text together with its programmatically determined context.

**Trusted Tester ID:**

- [ ]  Test 6.A link-purpose
