### ISSUE TITLE
1.3.3 Sensory Characteristics (A)

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#78]
**Were violation(s) found?**
(If Yes, describe in the comments.)
- [ ] No violations found
- [ ] Yes, violations found and all fixed
- [ ] Yes, violations found and some fixed while others are unresolved _(Add **6.Unresolved 508** label)_
- [ ] Yes, violations found but are remain unresolved _(Add **6.Unresolved 508** label)_
- [ ] Flag as a potential problem _(Add **4.Help** label)_

---
### 1.3.3 Sensory Characteristics - Level A
Instructions provided for understanding and operating content do not rely solely on sensory characteristics of components such as shape, color, size, visual location, orientation, or sound.

[Understanding 1.3.3](https://www.w3.org/WAI/WCAG21/Understanding/sensory-characteristics.html)
[How to Meet 1.3.3](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=131%2C211%2C212#sensory-characteristics)
[How to Test 1.3.3](https://usfs.box.com/s/8q6mf7c5xpn73zhfwdi0pgnijgfs4lvf)

**Trusted Tester ID:**
- [ ] Test 13.B sensory-info

**Accessibility Principle:** Perceivable (Adaptable)

**Comment by AlanaBayless** [comment]
All three pages passes 1.3.3 Sensory Characteristics, the pages do not solely rely on sensory characteristics of components to provide instructions
