### ISSUE TITLE
2.4.2 Page Titled (A)

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#79]
**Were violation(s) found?**
(If Yes, describe in the comments.)
- [ ] No violations found
- [ ] Yes, violations found and all fixed
- [ ] Yes, violations found and some fixed while others are unresolved _(Add **6.Unresolved 508** label)_
- [ ] Yes, violations found but are remain unresolved _(Add **6.Unresolved 508** label)_
- [ ] Flag as a potential problem _(Add **4.Help** label)_

---
### 2.4.2 Page Titled - Level A
Web pages have titles that describe topic or purpose.

[Understanding 2.4.2](https://www.w3.org/WAI/WCAG21/Understanding/page-titled.html)
[How to Meet 2.4.2](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=131%2C133%2C141%2C143%2C211%2C212%2C221%2C231#page-titled)
[How to Test 2.4.2](https://usfs.box.com/s/ar0ms8d8i3lwnzsnq2hjbjqrnr2wxuxu)

**Trusted Tester IDs:**
- [x] Test 12.A page-title-defined
- [x] Test 12.B page-title-purpose

**Accessibility Principle:** Operable (Navigable)

**Comment by AlanaBayless** [comment]
All three pages pass 2.4.2 Page Titled, A <title> element is defined for the Web page (12.A) and identifies the contents or purpose of the web page (12.B).
