### ISSUE TITLE
1.4.4 Resize Text (AA)

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#82]
### 1.4.4 Resize Text - Level AA
Except for captions and images of text, text can be resized without assistive technology up to 200 percent without loss of content or functionality.

[Understanding 1.4.4](https://www.w3.org/WAI/WCAG21/Understanding/resize-text.html)
[How to Meet 1.4.4](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=131%2C133%2C141%2C143%2C211%2C212#resize-text)
[How to Test 1.4.4](https://usfs.box.com/s/qjwsvodd6bymv12npipdcd0xn6l38ojp)

**Trusted Tester ID:**
- [x] Test 18.A resize-text

**Accessibility Principle:** Perceivable (Distinguishable)

**Comment by AlanaBayless** [comment]
All three pages pass 1.4.4 Resize Text, when the page are zoomed to 200 percent the contents and functionality is not lost.
