### ISSUE TITLE
3.3.3 Error Suggestion (AA)

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#83]
### 3.3.3 Error Suggestion - Level AA
If an input error is automatically detected and suggestions for correction are known, then the suggestions are provided to the user, unless it would jeopardize the security or purpose of the content.

[Understanding 3.3.3](https://www.w3.org/WAI/WCAG21/Understanding/error-suggestion.html)
[How to Meet 3.3.3](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=131%2C133%2C141%2C143%2C211%2C212%2C221%2C231%2C242%2C245%2C246%2C247%2C312%2C322%2C333#error-suggestion)
[How to Test 3.3.3](https://usfs.box.com/s/ef9cpv0aqlnmwovhql9sim7pri5hsscw)

**Trusted Tester ID:**
- [x] Test 5.G error-suggestion

**Accessibility Principle:** Understandable (Input Assistance)

**Comment by AlanaBayless** [comment]
There is no automatic input error detection on the pages, therefore it DNA to 3.3.3 Error Suggestion.
