### ISSUE TITLE
2.4.5 Multiple Ways (AA)

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#84]
### 2.4.5 Multiple Ways - Level AA
More than one way is available to locate a Web page within a set of Web pages except where the Web Page is the result of, or a step in, a process.

[Understanding 2.4.5](https://www.w3.org/WAI/WCAG21/Understanding/multiple-ways.html)
[How to Meet 2.4.5](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=131%2C133%2C141%2C143%2C211%2C212%2C221%2C231%2C242#multiple-ways)
[How to Test 2.4.5](https://usfs.box.com/s/w822nm2wz3d4a5pjffiewjiuqrdlw920)

**Trusted Tester ID:**
- [x] Test 19.A multiple-ways

**Accessibility Principle:** Operable (Navigable)

**Comment by AlanaBayless** [comment]
All three pages pass 2.4.5 Multiple Ways, there is more than one way is available to locate a Web page within the set of Web pages.
